apiVersion: v1
kind: Service
metadata:
  name: cray-hms-hmcollector-ingress
  labels:
    app.kubernetes.io/name: cray-hms-hmcollector-ingress
  {{- if eq .Values.service.type "LoadBalancer" }}
  annotations:
    metallb.universe.tf/address-pool: hardware-management
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.hmcollector_external_ip }}
  {{- end }}
  ports:
    - port: 80
      targetPort: hmc-insecure
      name: hmc-proxy-insecure
      protocol: TCP
  selector:
    app.kubernetes.io/name: cray-hms-hmcollector-ingress
