---
global:
  appVersion: 2.37.0

image:
  repository: artifactory.algol60.net/csm-docker/stable/hms-hmcollector
  pullPolicy: IfNotPresent

# These two fields will get overwritten by customizations.yaml.
# See https://github.com/Cray-HPE/csm/blob/main/vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml for more details.
hmcollector_external_ip: "10.94.100.71"
hmcollector_external_hostname: ""  # This field is system specific, and in the form of mcollector.hmnlb.<system-name>.<site-domain>

podAnnotations: {}
# For example, override the default Istio sidecar proxy memory limit:
# podAnnotations:
#   sidecar.istio.io/proxyMemoryLimit: 5Gi

collectorIngressConfig:
  replicas: 3
  logLevel: "INFO"

  pollingEnabled: "false"
  pollingInterval: "30"
  pduPollingInterval: "30"

  redfishSubscribeEnabled: "false"
  redfishStreamingEnabled: "false"
  restEnabled: "true"

  hsmRefreshInterval: "30"

  vaultEnabled: "false"

  resources:
    limits:
      cpu: "4"
      memory: 5Gi
    requests:
      cpu: 500m
      memory: 256Mi

collectorPollConfig:
  replicas: 1
  logLevel: "INFO"

  pollingEnabled: "true"
  pollingInterval: "30"
  pduPollingInterval: "30"

  redfishSubscribeEnabled: "true"
  redfishStreamingEnabled: "true"
  restEnabled: "false"

  hsmRefreshInterval: "30"

  vaultEnabled: "true"

  pruneOldSubscriptions: "true"

  resources:
    limits:
      cpu: "4"
      memory: 5Gi
    requests:
      cpu: 500m
      memory: 256Mi

gateway: hmn-gateway
service:
  type: ClusterIP
kafkaBrokers:
  - BrokerAddress: cluster-kafka-bootstrap.sma.svc.cluster.local:9092
    TopicsToPublish:
      - cray-telemetry-temperature
      - cray-telemetry-voltage
      - cray-telemetry-power
      - cray-telemetry-energy
      - cray-telemetry-fan
      - cray-telemetry-pressure
      - cray-telemetry-humidity
      - cray-telemetry-liquidflow
      - cray-telemetry-metric
      - cray-telemetry-powerfactor
      - cray-telemetry-frequency
      - cray-telemetry-percent
      - cray-fabric-telemetry
      - cray-fabric-perf-telemetry
      - cray-fabric-crit-telemetry
      - cray-dmtf-resource-event
      - cray-fabric-health
  - BrokerAddress: cray-shared-kafka-kafka-bootstrap.services.svc.cluster.local:9092
    TopicsToPublish:
      - cray-dmtf-resource-event
