---
global:
  appVersion: 2.16.0

image:
  repository: artifactory.algol60.net/csm-docker/stable/hms-hmcollector
  pullPolicy: IfNotPresent

# This will get overwritten by the correct Ansible value. See the hms-install repo for more details.
hmcollector_external_ip: "10.4.100.1"

podAnnotations: {}
# For example, override the default Istio sidecar proxy memory limit:
# podAnnotations:
#   sidecar.istio.io/proxyMemoryLimit: 5Gi

collectorIngressConfig:
  logLevel: "INFO"

  pollingEnabled: "false"
  pollingInterval: "30"
  pduPollingInterval: "30"

  redfishSubscribeEnabled: "false"
  redfishStreamingEnabled: "false"
  restEnabled: "true"

  hsmRefreshInterval: "30"

  vaultEnabled: "false"

  resources:
    limits:
      cpu: "4"
      memory: 5Gi
    requests:
      cpu: 500m
      memory: 256Mi

collectorPollConfig:
  logLevel: "INFO"

  pollingEnabled: "true"
  pollingInterval: "30"
  pduPollingInterval: "30"

  redfishSubscribeEnabled: "true"
  redfishStreamingEnabled: "true"
  restEnabled: "false"

  hsmRefreshInterval: "30"

  vaultEnabled: "true"

  resources:
    limits:
      cpu: "4"
      memory: 5Gi
    requests:
      cpu: 500m
      memory: 256Mi

gateway: hmn-gateway
service:
  type: ClusterIP
kafkaBrokers:
  - BrokerAddress: cluster-kafka-bootstrap.sma.svc.cluster.local:9092
    TopicsToPublish:
      - cray-telemetry-temperature
      - cray-telemetry-voltage
      - cray-telemetry-power
      - cray-telemetry-energy
      - cray-telemetry-fan
      - cray-telemetry-pressure
      - cray-telemetry-humidity
      - cray-telemetry-liquidflow
      - cray-fabric-telemetry
      - cray-fabric-perf-telemetry
      - cray-fabric-crit-telemetry
      - cray-dmtf-resource-event
  - BrokerAddress: cray-shared-kafka-kafka-bootstrap.services.svc.cluster.local:9092
    TopicsToPublish:
      - cray-dmtf-resource-event
