apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/instance: cray-hms-hmcollector-ingress
  name: cray-hms-hmcollector-ingress
spec:
  gateways:
  - {{ .Values.gateway }}
  hosts:
  - '{{ .Values.hmcollector_external_ip }}'
  {{- if .Values.hmcollector_external_hostname }}
  - '{{ .Values.hmcollector_external_hostname }}'
  {{ end }}
  http:
  - route:
    - destination:
        host: cray-hms-hmcollector-ingress
        port:
          number: 80
